const imageAssets = {
  splashBackground: require("../assets/images/backgrounds/viceroy-bali.jpg.jpg"),
  starterBackground: require("../assets/images/backgrounds/viceroy-bali.jpg.jpg"),
  notificationIcon: require("../assets/images/icons/notification.png"),
  backArrow: require("../assets/images/icons/left-arrow.png"),
  dropDownArrow: require("../assets/images/icons/drop-down-arrow.png"),
  closeIcon: "close",
  searchIcon: require("../assets/images/icons/magnifying-glass.png"),
  loadingIcon: require("../assets/images/loaders/loader.gif"),
  hamburgerIcon: require("../assets/images/icons/menu.png"),
  headerBackgroundShape: require("../assets/images/shapes/banner_white.png"),
  aeroplaneIcon: "flight",
  busIcon: "bus",
  ferryIcon: "ferry",
  trainIcon: "train",
  activityIcon: "activity",
  hotelIcon: "hotel",
  clockIcon: "clock",
  locationIcon: "location",
  semiCircleShape: require("../assets/images/shapes/hiring_topic.png"),

  tripFeedIcon: "trip-feed",
  tripFeedSelectedIcon: "trip-feed-active",
  bookingIcon: "booking",
  bookingSelectedIcon: "booking-active",
  supportIcon: "support",
  supportSelectedIcon: "support-active",
  toolIcon: "tools",
  toolSelectedIcon: "tools-active",
  journalIcon: "journal",
  journalSelectedIcon: "journal-active",
  moreOptionsHorizIcon: "more-options-horiz",
  arrowRight: "arrow-right"
};

export default imageAssets;
