const imageAssets = {
  splashBackground: require("../assets/images/backgrounds/viceroy-bali.jpg.jpg"),
  starterBackground: require("../assets/images/backgrounds/viceroy-bali.jpg.jpg"),
  notificationIcon: require("../assets/images/icons/notification.png"),
  backArrow: require("../assets/images/icons/left-arrow.png"),
  dropDownArrow: require("../assets/images/icons/drop-down-arrow.png"),
  closeIcon: "close",
  searchIcon: require("../assets/images/icons/magnifying-glass.png"),
  loadingIcon: require("../assets/images/loaders/loader.gif"),
  hamburgerIcon: require("../assets/images/icons/menu.png"),
  headerBackgroundShape: require("../assets/images/shapes/banner_white.png"),
  aeroplaneIcon: "flight",
  busIcon: "bus",
  ferryIcon: "ferry",
  trainIcon: "train",
  activityIcon: "activity",
  hotelIcon: "hotel",
  clockIcon: "clock",
  locationIcon: "location",
  semiCircleShape: require("../assets/images/shapes/hiring_topic.png"),

  tripFeedIcon: "trip-feed",
  tripFeedSelectedIcon: "trip-feed-active",
  bookingIcon: "booking",
  bookingSelectedIcon: "booking-active",
  supportIcon: "support",
  supportSelectedIcon: "support-active",
  toolIcon: "tools",
  toolSelectedIcon: "tools-active",
  journalIcon: "journal",
  journalSelectedIcon: "journal-active",
  moreOptionsHorizIcon: "more-options-horiz",
  arrowRight: "arrow-right",

  weatherGraphInactive: require("../assets/images/weatherPlaceholders/weather-graph-disabled.png"),
  weatherCardPlaceholder: require("../assets/images/weatherPlaceholders/weather-placeholder.png"),

  weatherForecastIcon: require("../assets/images/toolIcons/weather-forcast.png"),
  cancelTripIcon: require("../assets/images/toolIcons/cancel-trip.png"),
  commonPhrasesIcon: require("../assets/images/toolIcons/common-phrases.png"),
  completePaymentIcon: require("../assets/images/toolIcons/complete-payment.png"),
  currencyCalculatorIcon: require("../assets/images/toolIcons/currency-calculator.png"),
  documentVisaIcon: require("../assets/images/toolIcons/document-visa.png"),
  downloadInvoiceIcon: require("../assets/images/toolIcons/download-invoice.png"),
  emergencyContactsIcon: require("../assets/images/toolIcons/emergency-contacts.png"),
  faqIcon: require("../assets/images/toolIcons/faq.png"),
  invitePassengersIcon: require("../assets/images/toolIcons/invite-co-passanger.png"),
  medicalCareIcon: require("../assets/images/toolIcons/medical-care.png"),
  packageChecklistIcon: require("../assets/images/toolIcons/packing-checklist.png"),
  passportDetailsIcon: require("../assets/images/toolIcons/passport-details.png")
};

export default imageAssets;
