# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pickyourtrail' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Pickyourtrail
  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    'jschelpers',
    'cxxreact',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTWebSocket',
  ]
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'

  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'
  # export PATH="$PATH:/Users/mac/.nvm/versions/node/v9.11.1/bin"
  # target 'Pickyourtrail-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing

  # end

  # target 'PickyourtrailTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end

# target 'Pickyourtrail-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for Pickyourtrail-tvOS

#   target 'Pickyourtrail-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end