require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Pickyourtrail' do
  config = use_native_modules!
  
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Performance'
  
  pod 'RNKeychain', :path => '../node_modules/react-native-keychain'
  
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

    
  use_react_native!(:path => config["reactNativePath"])

  pod 'Interactable', :path => '../node_modules/react-native-interactable'

  target 'PickyourtrailTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Pickyourtrail-tvOS' do
  # Pods for Pickyourtrail-tvOS

  target 'Pickyourtrail-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
