# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
# pri -> change enterprise.xcodeproj to voyager

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Pickyourtrail.xcodeproj")
    get_certificates(
      output_path: "./builds"
    )
    get_provisioning_profile(
      output_path: "./builds",
      filename: "provisioning.mobileprovision"
    )
    build_app(
      workspace: "Pickyourtrail.xcworkspace",
      scheme: "Pickyourtrail",
      clean: true,
      export_method: "app-store",
      build_path: "./builds",
      output_directory: "./builds"
    )
    upload_to_testflight
  end
end
