export enum IGeneralCostingStatusEnum {
  SUCCESS = "SUCCESS",
  USER_REMOVED = "USER_REMOVED",
  NOT_COSTED = "NOT_COSTED",
  ERROR = "ERROR",
  UNAVAILABLE = "UNAVAILABLE",
  BLOCKED = "BLOCKED",
  SOLD_OUT = "SOLD_OUT",
  ROOM_SOLD_OUT = "ROOM_SOLD_OUT"
}
