# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Play Store"
  lane :beta do
    releaseFilePath = File.join(Dir.pwd, "..", "my-release-key.keystore")
    gradle(task: 'clean')
    gradle(
      task: 'assemble',
      build_type: 'Release',
      print_command: false
    )
    upload_to_play_store(
      track: 'internal',
      release_status: 'draft'
    )
    end

    desc "Submit a new prod Build to Play Store"
    lane :playstore do
    releaseFilePath = File.join(Dir.pwd, "..", "my-release-key.keystore")
    gradle(task: 'clean bundleRelease')
    gradle(
      task: 'assemble',
      build_type: 'Release',
      print_command: false
    )
    upload_to_play_store(
      track: 'production',
      release_status: 'draft',
      skip_upload_aab: true
    )
    end
end
