name: build
on: [ pull_request ]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12'
    - run: yarn install
    - run: yarn test  
  android_bundle:
    needs: [ test ]
    name: android-bundle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12'
    - run: yarn install
    - run: yarn run build-android-alpha
    - uses: actions/upload-artifact@master
      with:
        name: app.aab
        path: android/app/build/outputs/bundle/release/app.aab
